name: fix code styling

on:
  workflow_call:
    inputs:
      php:
        description: 'PHP version to use.'
        default: "8.4"
        type: string
      extensions:
        description: 'Extensions to pass to `shivammathur/setup-php`.'
        default: ''
        type: string
      tools:
        description: 'Tools to pass to `shivammathur/setup-php`.'
        default: 'composer:v2'
        type: string
      message:
        description: This value is used when committing changes (`fix` is true)
        default: Fix code style issues
        type: string
      fix:
        default: true
        type: boolean
      preset:
        description: The preset to use, defaults to `laravel`
        default: laravel
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: ${{ inputs.extensions }}
          tools: ${{ inputs.tools }}
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint (fix)
        if: ${{ inputs.fix }}
        run: pint --verbose --preset="${{ inputs.preset }}"

      - name: Run Pint (test)
        if: ${{ !inputs.fix }}
        run: pint --verbose --preset="${{ inputs.preset }}" --test

      - name: Commit linted files
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ inputs.message }}
