name: fix code styling

on:
  workflow_call:
    inputs:
      php:
        default: "8.4"
        type: string
      message:
        description: This value is used when committing changes (`fix` is true)
        default: Fix code style issues
        type: string
      fix:
        default: true
        type: boolean
      preset:
        description: The preset to use, defaults to `laravel`
        default: laravel
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: |
          PRESET="${{ inputs.preset }}"
          
          if [[ ! "${{ inputs.fix }}" ]]; then
              pint --verbose --preset="$PRESET"
          else
              pint --verbose --preset="$PRESET" --test
          fi

      - name: Commit linted files
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ inputs.message }}
