name: create auth json file

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  make-auth:
    runs-on: ubuntu-latest

    name: "Create auth.json file"


    steps:
      - name: Create auth.json file
        run: |
          echo '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}"}}}' > auth.json

      - name: Upload the file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: reusable-file
          path: auth.json
