name: Release Drafter

on:
  workflow_call:
    secrets:
      PAT:
        required: true
        description: '`GITHUB_TOKEN` with write permissions'

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
