name: Run Tests

on:
  workflow_call:
    inputs:
      php:
        description: 'JSON array of PHP versions to use. Defaults to `["8.4"]`.'
        default: '["8.4"]'
        type: string
      extensions:
        description: 'Extensions to pass to `shivammathur/setup-php`.'
        default: ''
        type: string
      tools:
        description: 'Tools to pass to `shivammathur/setup-php`.'
        default: 'composer:v2'
        type: string
      dependency-version:
        description: 'Composer dependency strategy: stable | lowest | highest.'
        default: 'stable'
        type: string
      pest:
        default: true
        description: 'Run tests with Pest, fall back to PHPUnit if false'
        required: false
        type: boolean
      parallel:
        default: false
        description: 'Run tests in parallel (for Pest only)'
        required: false
        type: boolean

jobs:
  test:
    strategy:
      matrix:
        php: ${{ fromJson(inputs.php) }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ inputs.extensions }}
          tools: ${{ inputs.tools }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ubuntu-latest-php-${{ matrix.php }}-composer-${{ inputs.dependency-version }}-${{ hashFiles('**/composer.lock') }}

      - name: Install PHP dependencies
        run: |
          case "${{ inputs.dependency-version }}" in
            lowest)
              composer update --prefer-lowest --prefer-stable --prefer-dist --no-progress --no-interaction --optimize-autoloader
              ;;
            highest)
              composer update --prefer-stable --prefer-dist --no-progress --no-interaction --optimize-autoloader
              ;;
            *)
              composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader
              ;;
          esac

      - name: Run with Pest
        if: ${{ inputs.pest }}
        run: vendor/bin/pest --ci ${{ inputs.parallel && '--parallel' || '' }}

      - name: Run with PHPUnit
        if: ${{ !inputs.pest }}
        run: vendor/bin/phpunit
