name: "Update Changelog"

on:
  workflow_call:
    inputs:
      target_commitish:
        type: string
        description: 'The commitish value that determines what commit the workflow will run against'
        required: false
        default: ${{ github.event.release.target_commitish }}
      tag_name:
        type: string
        description: 'The tag name of the release'
        required: false
        default: ${{ github.event.release.tag_name }}
      body:
        type: string
        description: 'The release notes of the release'
        required: false
        default: ${{ github.event.release.body }}

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the 
      # updated CHANGELOG back to the repository.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_commitish }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ inputs.tag_name }}
          release-notes: ${{ inputs.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ inputs.target_commitish }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md