name: update changelog

# Extracted from Laravel's `update-changelog` workflow
# https://github.com/laravel/.github/blob/main/.github/workflows/update-changelog.yml

on:
  workflow_call:
    inputs:
      branch:
        description: 'Target branch'
        default: ${{ github.event.release.target_commitish }}
        type: string
      version:
        description: 'Released version'
        default: ${{ github.event.release.tag_name }}
        type: string
      notes:
        description: 'Release notes'
        default: ${{ github.event.release.body }}
        type: string
      pr-title:
        description: 'PR title'
        default: 'Update `CHANGELOG`'
        type: string
      update-branch:
        description: 'PR branch'
        default: docs/update-changelog
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Extract release date from git tag
        id: release_date
        run: |
          # Get UNIX timestamp from git-tag
          TIMESTAMP_OF_RELEASE_COMMIT=$(git log -1 --date=unix --format=%ad '${{ inputs.version }}');

          # Convert timestamp to UTC date in Y-m-d format
          FORMATED_DATE=$(date -u -d @$TIMESTAMP_OF_RELEASE_COMMIT +%Y-%m-%d)

          # Make date available to other steps
          echo "date=$(echo $FORMATED_DATE)" >> $GITHUB_OUTPUT;

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-date: ${{ steps.release_date.outputs.date }}
          release-notes: ${{ inputs.notes }}
          latest-version: ${{ inputs.version }}
          compare-url-target-revision: ${{ inputs.branch }}
          parse-github-usernames: true

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ inputs.update-branch }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
          create_branch: true

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: ${{ inputs.pr-title }}
          base: main
          branch: ${{ inputs.update-branch }}
